local Players = game:GetService("Players")

Players.PlayerAdded:Connect(function(Player)
	task.wait(1)
	print(1)
	task.wait(2)
	print(2)
	task.wait(3)
	print(3)
	Player:Kick("Not Available Due To Hyperion: RCONSOLE not supported.")
end)
